"""initial schema: tenancy, identity, people, academic, assessment, report cards, audit

Revision ID: 9e07a1545e61
Revises: 
Create Date: 2026-09-12 01:48:44.980844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 -- used by rendered JSONB columns
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e07a1545e61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_templates',
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('curriculum', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_key')
    )
    op.create_table('permissions',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('platform_users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('platform_admin','platform_support')", name='ck_platform_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_users_email'), ['email'], unique=True)

    op.create_table('schools',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subdomain', sa.Text(), nullable=False),
    sa.Column('curriculum_mode', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("curriculum_mode in ('ges','cambridge','hybrid')", name='ck_schools_curriculum_mode'),
    sa.CheckConstraint("status in ('trial','active','suspended','archived')", name='ck_schools_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_subdomain'), ['subdomain'], unique=True)

    op.create_table('academic_years',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_years_school_name')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_academic_years_school_current', ['school_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_years_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_components',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("scope in ('term','year')", name='ck_components_scope'),
    sa.CheckConstraint('max_score > 0', name='ck_components_max_score'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_assessment_components_school_code')
    )
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_components_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_settings',
    sa.Column('weight_interpretation', sa.Text(), nullable=False),
    sa.Column('rounding_mode', sa.Text(), nullable=False),
    sa.Column('rounding_decimals', sa.Integer(), nullable=False),
    sa.Column('missing_score_rule', sa.Text(), nullable=False),
    sa.Column('absent_rule', sa.Text(), nullable=False),
    sa.Column('position_basis', sa.Text(), nullable=False),
    sa.Column('position_scope', sa.Text(), nullable=False),
    sa.Column('tie_rule', sa.Text(), nullable=False),
    sa.Column('aggregate_method', sa.Text(), nullable=False),
    sa.Column('best_n', sa.Integer(), nullable=True),
    sa.Column('best_n_compulsory_subject_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pass_mark', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('require_approval_before_publish', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("aggregate_method in ('mean_of_totals','sum_of_best_n_points','weighted_mean')", name='ck_settings_aggregate'),
    sa.CheckConstraint("rounding_mode in ('none','half_up','half_even')", name='ck_settings_rounding'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_assessment_settings_school')
    )
    with op.batch_alter_table('assessment_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_settings_school_id'), ['school_id'], unique=False)

    op.create_table('attendance_settings',
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('backdate_window_days', sa.Integer(), nullable=False),
    sa.Column('notify_guardians_on_absence', sa.Boolean(), nullable=False),
    sa.Column('notification_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_attendance_settings_school')
    )
    with op.batch_alter_table('attendance_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_settings_school_id'), ['school_id'], unique=False)

    op.create_table('attendance_statuses',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('counts_as_present', sa.Boolean(), nullable=False),
    sa.Column('triggers_notification', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_attendance_statuses_school_code')
    )
    with op.batch_alter_table('attendance_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_statuses_school_id'), ['school_id'], unique=False)

    op.create_table('grade_scales',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('applies_to', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_grade_scales_school_name')
    )
    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_scales_school_id'), ['school_id'], unique=False)

    op.create_table('onboarding_progress',
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('step_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=True),
    sa.Column('template_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', name='uq_onboarding_progress_school')
    )
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_progress_school_id'), ['school_id'], unique=False)

    op.create_table('report_card_templates',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('show_position', sa.Boolean(), nullable=False),
    sa.Column('show_class_average', sa.Boolean(), nullable=False),
    sa.Column('show_attendance', sa.Boolean(), nullable=False),
    sa.Column('show_teacher_remark', sa.Boolean(), nullable=False),
    sa.Column('show_head_remark', sa.Boolean(), nullable=False),
    sa.Column('show_grade_key', sa.Boolean(), nullable=False),
    sa.Column('show_component_breakdown', sa.Boolean(), nullable=False),
    sa.Column('signature_blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'name', name='uq_report_card_templates_school_name')
    )
    with op.batch_alter_table('report_card_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_card_templates_school_id'), ['school_id'], unique=False)

    op.create_table('roles',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'key', name='uq_roles_school_key')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_school_id'), ['school_id'], unique=False)

    op.create_table('subjects',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='uq_subjects_school_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_school_id'), ['school_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('invited','active','suspended')", name='ck_users_status'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'email', name='uq_users_school_email'),
    sa.UniqueConstraint('school_id', 'phone', name='uq_users_school_phone')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_users_school_status', ['school_id', 'status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('old_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_school_created', ['school_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_school_entity', ['school_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_school_id'), ['school_id'], unique=False)

    op.create_table('grade_bands',
    sa.Column('grade_scale_id', sa.Uuid(), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('grade', sa.Text(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('points', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('min_score <= max_score', name='ck_grade_bands_range'),
    sa.ForeignKeyConstraint(['grade_scale_id'], ['grade_scales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grade_bands', schema=None) as batch_op:
        batch_op.create_index('ix_grade_bands_scale', ['school_id', 'grade_scale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_bands_school_id'), ['school_id'], unique=False)

    op.create_table('guardians',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('occupation', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_guardians_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_guardians_school_phone', ['school_id', 'phone'], unique=False)

    op.create_table('import_jobs',
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_school_id'), ['school_id'], unique=False)

    op.create_table('login_attempts',
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_school_id'), ['school_id'], unique=False)

    op.create_table('password_resets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_school_id'), ['school_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions')
    )
    op.create_table('staff',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('staff_code', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status in ('active','suspended','left')", name='ck_staff_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'staff_code', name='uq_staff_school_code')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_school_id'), ['school_id'], unique=False)

    op.create_table('students',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('student_code', sa.Text(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status in ('active','graduated','transferred','withdrawn')", name='ck_students_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_code', name='uq_students_school_code')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_students_school_last_name', ['school_id', 'last_name'], unique=False)
        batch_op.create_index('ix_students_school_status', ['school_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_status'), ['status'], unique=False)

    op.create_table('terms',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('results_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'sequence', name='uq_terms_year_sequence')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_terms_school_current', ['school_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_school_id'), ['school_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles')
    )
    op.create_table('classes',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('class_teacher_id', sa.Uuid(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('curriculum', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'academic_year_id', 'name', 'section', name='uq_classes_year_name_section')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_classes_school_level', ['school_id', 'level'], unique=False)
        batch_op.create_index('ix_classes_school_year', ['school_id', 'academic_year_id'], unique=False)

    op.create_table('result_remarks',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('author_role', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('written_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['written_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'term_id', 'author_role', name='uq_result_remarks_slot')
    )
    with op.batch_alter_table('result_remarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_remarks_school_id'), ['school_id'], unique=False)

    op.create_table('student_guardians',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Text(), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('can_pick_up', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'guardian_id', name='uq_student_guardian')
    )
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.create_index('ix_student_guardians_guardian', ['school_id', 'guardian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_guardians_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_scores',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['component_id'], ['assessment_components.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'subject_id', 'term_id', 'component_id', name='uq_assessment_score_slot')
    )
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_scores_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_scores_school_class_subject_term', ['school_id', 'class_id', 'subject_id', 'term_id'], unique=False)
        batch_op.create_index('ix_scores_school_class_term', ['school_id', 'class_id', 'term_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=True),
    sa.Column('status_code', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('marked_by', sa.Uuid(), nullable=True),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'date', 'period_id', name='uq_attendance_slot')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_attendance_school_class_date', ['school_id', 'class_id', 'date'], unique=False)
        batch_op.create_index('ix_attendance_school_student_term', ['school_id', 'student_id', 'term_id'], unique=False)

    op.create_table('class_subjects',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.Column('grade_scale_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_scale_id'], ['grade_scales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_id', 'subject_id', name='uq_class_subject')
    )
    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.create_index('ix_class_subjects_school_class', ['school_id', 'class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_subjects_school_id'), ['school_id'], unique=False)

    op.create_table('enrollment_history',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('from_class_id', sa.Uuid(), nullable=True),
    sa.Column('to_class_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_history_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_enrollment_history_student', ['school_id', 'student_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('active','promoted','repeated','transferred','withdrawn')", name='ck_enrollments_status'),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollments_school_class', ['school_id', 'class_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_status'), ['status'], unique=False)
        batch_op.create_index('uq_enrollments_active_student_year', ['school_id', 'student_id', 'academic_year_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    op.create_table('generated_report_cards',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['report_card_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'term_id', name='uq_generated_report_cards_slot')
    )
    with op.batch_alter_table('generated_report_cards', schema=None) as batch_op:
        batch_op.create_index('ix_generated_cards_school_class_term', ['school_id', 'class_id', 'term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_report_cards_school_id'), ['school_id'], unique=False)

    op.create_table('promotion_batches',
    sa.Column('source_class_id', sa.Uuid(), nullable=False),
    sa.Column('target_class_id', sa.Uuid(), nullable=False),
    sa.Column('promoted_count', sa.Integer(), nullable=False),
    sa.Column('retained_count', sa.Integer(), nullable=False),
    sa.Column('retained_student_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('executed_by', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promotion_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_batches_school_id'), ['school_id'], unique=False)

    op.create_table('report_card_jobs',
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status in ('queued','processing','completed','failed','partial')", name='ck_report_card_jobs_status'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_card_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_card_jobs_school_id'), ['school_id'], unique=False)

    op.create_table('results',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('grade', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('points', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('subject_position', sa.Integer(), nullable=True),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('component_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'subject_id', 'term_id', name='uq_results_slot')
    )
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.create_index('ix_results_school_class_term', ['school_id', 'class_id', 'term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_results_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_results_school_student_term', ['school_id', 'student_id', 'term_id'], unique=False)

    op.create_table('term_results',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('aggregate_method', sa.Text(), nullable=True),
    sa.Column('subjects_counted', sa.Integer(), nullable=False),
    sa.Column('overall_position', sa.Integer(), nullable=True),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'student_id', 'term_id', name='uq_term_results_slot')
    )
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.create_index('ix_term_results_school_class_term', ['school_id', 'class_id', 'term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_term_results_school_id'), ['school_id'], unique=False)

    op.create_table('class_subject_teachers',
    sa.Column('class_subject_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_subject_id'], ['class_subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'class_subject_id', 'staff_id', name='uq_class_subject_teacher')
    )
    with op.batch_alter_table('class_subject_teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_subject_teachers_school_id'), ['school_id'], unique=False)
        batch_op.create_index('ix_class_subject_teachers_staff', ['school_id', 'staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_subject_teachers', schema=None) as batch_op:
        batch_op.drop_index('ix_class_subject_teachers_staff')
        batch_op.drop_index(batch_op.f('ix_class_subject_teachers_school_id'))

    op.drop_table('class_subject_teachers')
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_results_school_id'))
        batch_op.drop_index('ix_term_results_school_class_term')

    op.drop_table('term_results')
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_index('ix_results_school_student_term')
        batch_op.drop_index(batch_op.f('ix_results_school_id'))
        batch_op.drop_index('ix_results_school_class_term')

    op.drop_table('results')
    with op.batch_alter_table('report_card_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_card_jobs_school_id'))

    op.drop_table('report_card_jobs')
    with op.batch_alter_table('promotion_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_batches_school_id'))

    op.drop_table('promotion_batches')
    with op.batch_alter_table('generated_report_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_report_cards_school_id'))
        batch_op.drop_index('ix_generated_cards_school_class_term')

    op.drop_table('generated_report_cards')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('uq_enrollments_active_student_year', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_enrollments_school_id'))
        batch_op.drop_index('ix_enrollments_school_class')

    op.drop_table('enrollments')
    with op.batch_alter_table('enrollment_history', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollment_history_student')
        batch_op.drop_index(batch_op.f('ix_enrollment_history_school_id'))

    op.drop_table('enrollment_history')
    with op.batch_alter_table('class_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_subjects_school_id'))
        batch_op.drop_index('ix_class_subjects_school_class')

    op.drop_table('class_subjects')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_school_student_term')
        batch_op.drop_index('ix_attendance_school_class_date')
        batch_op.drop_index(batch_op.f('ix_attendance_records_school_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_school_class_term')
        batch_op.drop_index('ix_scores_school_class_subject_term')
        batch_op.drop_index(batch_op.f('ix_assessment_scores_school_id'))

    op.drop_table('assessment_scores')
    with op.batch_alter_table('student_guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_guardians_school_id'))
        batch_op.drop_index('ix_student_guardians_guardian')

    op.drop_table('student_guardians')
    with op.batch_alter_table('result_remarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_remarks_school_id'))

    op.drop_table('result_remarks')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index('ix_classes_school_year')
        batch_op.drop_index('ix_classes_school_level')
        batch_op.drop_index(batch_op.f('ix_classes_school_id'))
        batch_op.drop_index(batch_op.f('ix_classes_deleted_at'))

    op.drop_table('classes')
    op.drop_table('user_roles')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_school_id'))
        batch_op.drop_index('ix_terms_school_current')
        batch_op.drop_index(batch_op.f('ix_terms_deleted_at'))

    op.drop_table('terms')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_status'))
        batch_op.drop_index('ix_students_school_status')
        batch_op.drop_index('ix_students_school_last_name')
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_index(batch_op.f('ix_students_deleted_at'))

    op.drop_table('students')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_school_id'))
        batch_op.drop_index(batch_op.f('ix_staff_deleted_at'))

    op.drop_table('staff')
    op.drop_table('role_permissions')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_school_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_jti'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_resets_school_id'))

    op.drop_table('password_resets')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_school_id'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_identifier'))

    op.drop_table('login_attempts')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_school_id'))

    op.drop_table('import_jobs')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index('ix_guardians_school_phone')
        batch_op.drop_index(batch_op.f('ix_guardians_school_id'))
        batch_op.drop_index(batch_op.f('ix_guardians_phone'))
        batch_op.drop_index(batch_op.f('ix_guardians_deleted_at'))

    op.drop_table('guardians')
    with op.batch_alter_table('grade_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_bands_school_id'))
        batch_op.drop_index('ix_grade_bands_scale')

    op.drop_table('grade_bands')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_school_id'))
        batch_op.drop_index('ix_audit_logs_school_entity')
        batch_op.drop_index('ix_audit_logs_school_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_school_status')
        batch_op.drop_index(batch_op.f('ix_users_school_id'))

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_school_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_deleted_at'))

    op.drop_table('subjects')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_school_id'))

    op.drop_table('roles')
    with op.batch_alter_table('report_card_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_card_templates_school_id'))

    op.drop_table('report_card_templates')
    with op.batch_alter_table('onboarding_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_progress_school_id'))

    op.drop_table('onboarding_progress')
    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_scales_school_id'))

    op.drop_table('grade_scales')
    with op.batch_alter_table('attendance_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_statuses_school_id'))

    op.drop_table('attendance_statuses')
    with op.batch_alter_table('attendance_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_settings_school_id'))

    op.drop_table('attendance_settings')
    with op.batch_alter_table('assessment_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_settings_school_id'))

    op.drop_table('assessment_settings')
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_components_school_id'))

    op.drop_table('assessment_components')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_school_id'))
        batch_op.drop_index('ix_academic_years_school_current')
        batch_op.drop_index(batch_op.f('ix_academic_years_deleted_at'))

    op.drop_table('academic_years')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_subdomain'))
        batch_op.drop_index(batch_op.f('ix_schools_status'))

    op.drop_table('schools')
    with op.batch_alter_table('platform_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_users_email'))

    op.drop_table('platform_users')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    op.drop_table('curriculum_templates')
    # ### end Alembic commands ###
